<?php

use Drupal\tasty_backend_base\TastyBackendManager;

/**
 * Implements hook_toolbar_alter().
 */
function tasty_backend_base_toolbar_alter(&$items) {
  
  // Remove the administration menu.
  $roles = \Drupal::currentUser()->getRoles();
  if (!in_array('administrator', $roles)) {
    $items['administration']['tab']['#access'] = FALSE;
  }
  
  // Add icons css.
  $items['toolbar_menu_tb_manage']['#attached']['library'][] = 'tasty_backend_base/tasty_backend_icons';
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function tasty_backend_base_menu_links_discovered_alter(&$links) {

  // Add node links for each content type.
  foreach (\Drupal::entityTypeManager()->getStorage('node_type')->loadMultiple() as $type) {
    $links['tasty_backend_base.node.add.' . $type->id()] = array(
      'title' => t($type->label()),
      'route_name' => 'node.add',
      'parent' => 'tasty_backend_base.add_content',
      'menu_name' => 'tb-manage',
      'route_parameters' => array('node_type' => $type->id()),
    );
  }

  // Links for taxonomy vocabularies.
  foreach (\Drupal\taxonomy\Entity\Vocabulary::loadMultiple() as $vocab) {
    $links['tasty_backend_base.entity.taxonomy_vocabulary.overview_form.' . $vocab->id()] = array(
      'title' => t($vocab->label()),
      'route_name' => 'entity.taxonomy_vocabulary.overview_form',
      'parent' => 'tasty_backend_base.taxonomy_vocabulary.collection',
      'menu_name' => 'tb-manage',
      'route_parameters' => array('taxonomy_vocabulary' => $vocab->id()),
    );
    $links['tasty_backend_base.entity.taxonomy_term.add_form.' . $vocab->id()] = array(
      'title' => t('Add term'),
      'route_name' => 'entity.taxonomy_term.add_form',
      'parent' => 'tasty_backend_base.entity.taxonomy_vocabulary.overview_form.' . $vocab->id(),
      'menu_name' => 'tb-manage',
      'route_parameters' => array('taxonomy_vocabulary' => $vocab->id()),
    );
  }

  // Links for menus.
  foreach (menu_ui_get_menus() as $machine_name => $label) {
    $links['tasty_backend_base.entity.menu.edit_form.' . $machine_name] = array(
      'title' => $label,
      'route_name' => 'entity.menu.edit_form',
      'menu_name' => 'tb-manage',
      'parent' => 'tasty_backend_base.menu.collection',
      'route_parameters' => array('menu' => $machine_name),
    );
    $links['tasty_backend_base.entity.menu.add_link_form.' . $machine_name] = array(
      'title' => t('Add link'),
      'route_name' => 'entity.menu.add_link_form',
      'menu_name' => 'tb-manage',
      'parent' => 'tasty_backend_base.entity.menu.edit_form.' . $machine_name,
      'route_parameters' => array('menu' => $machine_name),
    );
  }
}

/**
 * Implements hook_entity_bundle_create().
 */
function tasty_backend_base_entity_bundle_create($entity_type_id, $bundle) {

  if ($entity_type_id == 'node') {
    $type = \Drupal::entityTypeManager()->getStorage('node_type')->load($bundle);

    // Add the management view.
    TastyBackendManager::addAdminView($type);

    // Add permissions to the content admin role.
    if (\Drupal::config('tasty_backend_base.settings')->get('apply_default_content_perms')) {
      TastyBackendManager::addContentTypePermissions($type);
    }
  }

  // Add default vocabulary permissions to the content admin role.
  if ($entity_type_id == 'taxonomy_term' && \Drupal::config('tasty_backend_base.settings')->get('apply_default_vocab_perms')) {
    $vocabulary = \Drupal::entityTypeManager()->getStorage('taxonomy_vocabulary')->load($bundle);
    TastyBackendManager::addVocabularyPermissions($vocabulary);
  }
}

/**
 * Implements hook_entity_bundle_delete().
 */
function tasty_backend_base_entity_bundle_delete($entity_type_id, $bundle) {

  if ($entity_type_id == 'node') {
    $storage_handler = \Drupal::entityTypeManager()->getStorage('view');
    $entities = $storage_handler->loadMultiple(['tb_manage_content_' . $bundle]);
    $storage_handler->delete($entities);
  }
}
